### ISSUE TITLE
Creating circle duo to doc fails

### ISSUE THREAD

**Issue by Fuzzyma** [tmpvar/circle2#3]
According to doc
>new Circle([origin [, radius])

>Where origin adheres to the following form:

>    [0, 1]
>    { x: 0, y: 1}

this should work: `Circle([0,1], 5)`
Same with: `Circle({x:0, y:1}, 5)`

Both throw an error in deeper Code.
Something I do wrong?

**Comment by tmpvar** [comment]
nice catch! this will go out with the next release

**Comment by tmpvar** [comment]
published in v1.1.1
