### ISSUE TITLE
When only one intersection point is returned, its not an array

### ISSUE THREAD

**Issue by Fuzzyma** [tmpvar/circle2#4]
The doc points out the following:

>Performs an intersection between this circle and the incoming. Results are as follows:
>- [Vec2] - single intersection
>- [Vec2, Vec2] - two intersection points

But in reality the code returns the plain `Vec2` when only one intersection is detected

**Comment by tmpvar** [comment]
thank you for reporting this, I'll push this out in the next release

**Comment by tmpvar** [comment]
published in v1.1.1
